### ISSUE TITLE
Broken quota unit tests, presumably because of 2017 NY bug

### ISSUE THREAD

**Issue by rafatower** [CartoDB/dataservices-api#335]
Both in master and development branches:
```
ubuntu@cdb:~/src/dataservices-api/server/lib/python/cartodb_services$ nosetests test/
...................................FF...............................................................................................
======================================================================
FAIL: I have 1000 credits and I just spent 1000 today. I should not pass
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/src/dataservices-api/server/lib/python/cartodb_services/test/metrics/test_quota.py", line 71, in test_routing_quota_check_fails_right_in_the_limit
    assert checker.check() == False
AssertionError

======================================================================
FAIL: test_routing_quota_check_fails_when_quota_exhausted (test.metrics.test_quota.TestQuotaChecker)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/src/dataservices-api/server/lib/python/cartodb_services/test/metrics/test_quota.py", line 53, in test_routing_quota_check_fails_when_quota_exhausted
    assert checker.check() == False
AssertionError

----------------------------------------------------------------------
Ran 132 tests in 0.319s

FAILED (failures=2)
```

**Comment by rafatower** [comment]
There's a bug calculating the billing cycles in `__current_billing_cycle`:
```
> /home/ubuntu/src/dataservices-api/server/lib/python/cartodb_services/cartodb_services/metrics/user.py(81)__used_routing_quota()
-> date_from, date_to = self.__current_billing_cycle()
(Pdb) date_from
*** NameError: name 'date_from' is not defined
(Pdb) n
> /home/ubuntu/src/dataservices-api/server/lib/python/cartodb_services/cartodb_services/metrics/user.py(82)__used_routing_quota()
-> current_use = 0
(Pdb) date_from
datetime.date(2017, 1, 3)
(Pdb) date_to
datetime.date(2017, 1, 3)
(Pdb) 
```

**Comment by rafatower** [comment]
In retrospective I think that `latest_valid_date` is a big smell when calculating billing cycles: https://github.com/CartoDB/dataservices-api/blob/ebbfae95cfca9414a5af3734ddab868221036eae/server/lib/python/cartodb_services/cartodb_services/metrics/user.py#L161

**Comment by rafatower** [comment]
I tried a binary search of the problem but it was present from early versions of the code.

**Comment by rafatower** [comment]
It's a problem with just the unit tests :sweat_smile: 

With this patch:
```patch
diff --git a/server/lib/python/cartodb_services/cartodb_services/metrics/user.py b/server/lib/python/cartodb_services/cartodb_services/metrics/user.py
index 82aaf95..943c17c 100644
--- a/server/lib/python/cartodb_services/cartodb_services/metrics/user.py
+++ b/server/lib/python/cartodb_services/cartodb_services/metrics/user.py
@@ -118,6 +118,7 @@ class UserMetricsService:
         for date in self.__generate_date_range(date_from, date_to):
             redis_prefix = self.__parse_redis_prefix(key_prefix, entity_name,
                                                      service, metric, date)
+            print "SUT redis_prefix = {0}".format(redis_prefix)
             score = self._redis_connection.zscore(redis_prefix, date.day)
             aggregated_metric += int(score) if score else 0
             zero_padded_day = date.strftime(self.DAY_OF_MONTH_ZERO_PADDED)
diff --git a/server/lib/python/cartodb_services/test/metrics/test_quota.py b/server/lib/python/cartodb_services/test/metrics/test_quota.py
index 18f2105..21a8b9a 100644
--- a/server/lib/python/cartodb_services/test/metrics/test_quota.py
+++ b/server/lib/python/cartodb_services/test/metrics/test_quota.py
@@ -48,6 +48,7 @@ class TestQuotaChecker(TestCase):
             soft_limit = False
         )
         redis_conn = MockRedis()
+        print "Test redis_prefix = '{0}'".format(self.redis_key)
         redis_conn.zincrby(self.redis_key, self.period_end_date.day, 1001)
         checker = QuotaChecker(user_service_config, redis_conn)
         assert checker.check() == False
```

we can see it clearly:
```
$ nosetests test/metrics/test_quota.py:TestQuotaChecker.test_routing_quota_check_fails_when_quota_exhausted
F
======================================================================
FAIL: test_routing_quota_check_fails_when_quota_exhausted (test.metrics.test_quota.TestQuotaChecker)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rtorre/src/dataservices-api/server/lib/python/cartodb_services/test/metrics/test_quota.py", line 54, in test_routing_quota_check_fails_when_quota_exhausted
    assert checker.check() == False
AssertionError: 
-------------------- >> begin captured stdout << ---------------------
Test redis_prefix = 'user:my_test_user:routing_mapzen:success_responses:20171'
SUT redis_prefix = user:my_test_user:routing_mapzen:success_responses:201701
SUT redis_prefix = user:my_test_user:routing_mapzen:empty_responses:201701

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
```

The problem is that the month part of the redis key for the test is not zero-padded.

**Comment by rafatower** [comment]
## Acceptance criteria
- [ ] pass the unit tests
- [ ] check that metrics are stored in redis with zero-padded months in production from the Editor
- [ ] check that metrics are stored in redis with zero-padded months in production from Builder

**Comment by rafatower** [comment]
Related PR: https://github.com/CartoDB/dataservices-api/pull/337

**Comment by rafatower** [comment]
To check with the Editor I enabled it to a test user `rtorre6` and ran a geocode. Everything seems fine:
```
irb(main):001:0> $users_metadata.zscore 'user:rtorre6:geocoder_here:total_requests:201701', '04'
=> 93.0
irb(main):002:0> $users_metadata.zscore 'user:rtorre6:geocoder_here:total_requests:20171', '04'
=> nil
irb(main):003:0> $users_metadata.zscore 'user:rtorre6:geocoder_here:total_requests:20171', '4'
=> nil
irb(main):004:0> $users_metadata.zscore 'user:rtorre6:geocoder_here:total_requests:201701', '4'
=> nil
```

**Comment by rafatower** [comment]
Similar test with Builder enabled user:
```
irb(main):007:0> $users_metadata.zscore 'user:rtorre2:geocoder_mapzen:total_requests:201701', '04'
=> 20.0
irb(main):008:0> $users_metadata.zscore 'user:rtorre2:geocoder_mapzen:total_requests:20171', '04'
=> nil
irb(main):009:0> $users_metadata.zscore 'user:rtorre2:geocoder_mapzen:total_requests:20171', '4'
=> nil
irb(main):010:0> $users_metadata.zscore 'user:rtorre2:geocoder_mapzen:total_requests:201701', '4'
=> nil
```
