### ISSUE TITLE
Fix a few tests that fail between the 1st and the 9th of the month

### ISSUE THREAD

**Issue by rafatower** [CartoDB/dataservices-api#364]
They were broken when releasing the `python-0.14.1` which cleaned up old code (reading/writing non-zero-padded dates):
```
$ nosetests test/
...................................FF.............................................................................FF.........................F.........F
======================================================================
FAIL: I have 1000 credits and I just spent 1000 today. I should not pass
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rtorre_unencrypted/src/dataservices-api/server/lib/python/cartodb_services/test/metrics/test_quota.py", line 71, in test_routing_quota_check_fails_right_in_the_limit
    assert checker.check() == False
AssertionError

======================================================================
FAIL: test_routing_quota_check_fails_when_quota_exhausted (test.metrics.test_quota.TestQuotaChecker)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rtorre_unencrypted/src/dataservices-api/server/lib/python/cartodb_services/test/metrics/test_quota.py", line 53, in test_routing_quota_check_fails_when_quota_exhausted
    assert checker.check() == False
AssertionError

======================================================================
FAIL: test_should_return_false_if_org_quota_is_surpassed (test.test_quota_service.TestQuotaService)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rtorre_unencrypted/src/dataservices-api/server/lib/python/cartodb_services/test/test_quota_service.py", line 52, in test_should_return_false_if_org_quota_is_surpassed
    assert qs.check_user_quota() is False
AssertionError

======================================================================
FAIL: test_should_return_false_if_user_quota_is_surpassed (test.test_quota_service.TestQuotaService)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rtorre_unencrypted/src/dataservices-api/server/lib/python/cartodb_services/test/test_quota_service.py", line 45, in test_should_return_false_if_user_quota_is_surpassed
    assert qs.check_user_quota() is False
AssertionError

======================================================================
FAIL: test_org_used_quota_for_a_day (test.test_user_service.TestUserService)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rtorre_unencrypted/src/dataservices-api/server/lib/python/cartodb_services/test/test_user_service.py", line 35, in test_org_used_quota_for_a_day
    assert us.used_quota(self.NOKIA_GEOCODER, date.today()) == 400
AssertionError

======================================================================
FAIL: test_user_used_quota_for_a_day (test.test_user_service.TestUserService)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rtorre_unencrypted/src/dataservices-api/server/lib/python/cartodb_services/test/test_user_service.py", line 24, in test_user_used_quota_for_a_day
    assert us.used_quota(self.NOKIA_GEOCODER, date.today()) == 400
AssertionError

----------------------------------------------------------------------
Ran 152 tests in 0.134s

FAILED (failures=6)
```

**Comment by ethervoid** [comment]
Didn't happen anymore, so closing.
